### ISSUE TITLE
请教下，布置到服务器之后出现了如下的问题

### ISSUE THREAD

**Issue by beydeng** [shenhai/phpGrace#2]
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /data/www/htdocs/LX_Api/phpGrace/tools/db.php:28 Stack trace: #0 /data/www/htdocs/LX_Api/phpGrace/tools/db.php(28): PDO->__construct('mysql:host=loca...', 'root', 'xiangyin701') #1 /data/www/htdocs/LX_Api/phpGrace/tools/db.php(47): phpGrace\tools\db->__construct(Array) #2 /data/www/htdocs/LX_Api/phpGrace/phpGrace.php(102): phpGrace\tools\db::getInstance(Array, 'course', 'db') #3 /data/www/htdocs/LX_Api/phpGrace/phpGrace.php(467): db('course') #4 /data/www/htdocs/LX_Api/phpGrace/phpGrace.php(108): graceModel->__construct() #5 /data/www/htdocs/LX_Api/app/controllers/home.php(27): model('phpGrace\\models...') #6 /data/www/htdocs/LX_Api/phpGrace/phpGrace.php(516): homeController->home() #7 /data/www/htdocs/LX_Api/index.php(8): include('/data/www/htdoc...') #8 {main} thrown in /data/www/htdocs/LX_Api/phpGrace/tools/db.php on line 28

自己也查了几个小时的资料，服务器该弄的都弄了，实在是找不到原因，所以来劳烦，请教下

**Comment by balbeleet** [comment]
不是写了找不到文件了吗？ 你是不是权限的问题
